// client-react/src/views/ChatDetail.tsx
import { useState, useEffect, useRef, useCallback } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import {
  Brush,
  Camera,
  ChartBarIncreasing,
  ChevronLeft,
  File,
  Image,
  Mic,
  Paperclip,
  Send,
  Smile,
  UserRound,
} from 'lucide-react'
import { useUserStore } from '@/stores/user'
import { useChatStore, type ChatMessage } from '@/stores/chat'
import { messageApi } from '@/api/message'
import { userApi } from '@/api/user'
import { TimeDivider } from '@/components/ui/time-divider'
import { MessageBubble } from '@/components/ui/message-bubble'
import { ActionSheet } from '@/components/ui/action-sheet'
import { TemplateChatRightShell } from '@/components/ui/chat-template'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'

export default function ChatDetail() {
  const { userId } = useParams<{ userId: string }>()
  const navigate = useNavigate()
  const userStore = useUserStore()
  const chatStore = useChatStore()

  const peerId = userId || ''
  const myId = userStore.user?.id || ''

  // 过滤出当前对话的消息
  const messages = chatStore.messages.filter(
    (m: ChatMessage) =>
      ((m.senderId || m.fromUserId) === myId &&
        (m.receiverId || m.toUserId) === peerId) ||
      ((m.senderId || m.fromUserId) === peerId &&
        (m.receiverId || m.toUserId) === myId),
  )

  const [input, setInput] = useState('')
  const [showEmoji, setShowEmoji] = useState(false)
  const [showSheet, setShowSheet] = useState(false)
  const [isVoiceMode, setIsVoiceMode] = useState(false)
  const [isRecording, setIsRecording] = useState(false)
  const mediaRecorderRef = useRef<MediaRecorder | null>(null)
  const voiceChunksRef = useRef<Blob[]>([])

  async function startRecording() {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true })
      const mr = new MediaRecorder(stream, { mimeType: 'audio/webm;codecs=opus' })
      mediaRecorderRef.current = mr
      voiceChunksRef.current = []

      mr.ondataavailable = (e) => {
        if (e.data.size > 0) voiceChunksRef.current.push(e.data)
      }

      mr.onstop = async () => {
        stream.getTracks().forEach((t) => t.stop())
        const blob = new Blob(voiceChunksRef.current, { type: 'audio/webm' })
        if (blob.size < 100) return
        const fd = new FormData()
        fd.append('toUserId', peerId)
        fd.append('file', blob, `voice-${Date.now()}.webm`)
        fd.append('content', '')
        try {
          await messageApi.sendForm(fd)
          await chatStore.fetchMessages(peerId)
          setTimeout(() => scrollBottom(true), 100)
        } catch {
          /* noop */
        }
      }

      mr.start()
      setIsRecording(true)
    } catch {
      setIsVoiceMode(false)
      setIsRecording(false)
    }
  }

  function stopRecording() {
    if (mediaRecorderRef.current?.state === 'recording') {
      mediaRecorderRef.current.stop()
    }
    setIsRecording(false)
  }
  const [peerUser, setPeerUser] = useState<{
    nickname: string
    avatarUrl: string | null
  } | null>(null)
  const listRef = useRef<HTMLDivElement>(null)
  const pollRef = useRef<ReturnType<typeof setInterval> | undefined>(undefined)
  const connected = chatStore.connected
  const fetchMessages = chatStore.fetchMessages

  const stopPolling = useCallback(() => {
    if (pollRef.current) {
      clearInterval(pollRef.current)
      pollRef.current = undefined
    }
  }, [])

  const startPolling = useCallback(() => {
    if (pollRef.current || connected) return
    pollRef.current = setInterval(() => fetchMessages(peerId), 10000)
  }, [connected, fetchMessages, peerId])

  // 取对端用户信息
  useEffect(() => {
    if (!peerId) return
    userApi
      .get(peerId)
      .then((r) => setPeerUser(r.data.data))
      .catch(() => setPeerUser(null))
    fetchMessages(peerId)
    if (!connected) startPolling()
    return () => stopPolling()
  }, [peerId, connected, fetchMessages, startPolling, stopPolling])

  // 防止跟自己聊天
  useEffect(() => {
    if (peerId === myId) navigate('/messages', { replace: true })
  }, [peerId, myId, navigate])

  // 消息变化自动滚底
  useEffect(() => {
    scrollBottom()
  }, [messages.length])

  // socket 连接变化
  useEffect(() => {
    if (connected) stopPolling()
    else if (peerId) startPolling()
  }, [connected, peerId, startPolling, stopPolling])

  const peerNickname = peerUser?.nickname || '聊天'

  function scrollBottom(force = false) {
    const el = listRef.current
    if (!el) return
    if (force) {
      el.scrollTop = el.scrollHeight
      return
    }
    const atBottom = el.scrollHeight - el.scrollTop - el.clientHeight < 120
    if (atBottom) el.scrollTop = el.scrollHeight
  }

  async function send() {
    const text = input.trim()
    if (!text) return
    try {
      const res = await messageApi.send(peerId, text)
      useChatStore.setState((s) => ({
        messages: [...s.messages, res.data.data],
      }))
      setInput('')
      setTimeout(() => scrollBottom(true), 100)
    } catch {
      /* noop */
    }
  }

  // 文件选择
  const imageInputRef = useRef<HTMLInputElement>(null)
  const videoInputRef = useRef<HTMLInputElement>(null)
  const [uploadPreview, setUploadPreview] = useState('')
  const [uploadIsVideo, setUploadIsVideo] = useState(false)
  const [uploadFile, setUploadFile] = useState<File | null>(null)

  function onFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const f = e.target.files?.[0]
    if (f) {
      setUploadFile(f)
      setUploadPreview(URL.createObjectURL(f))
      setUploadIsVideo(f.type.startsWith('video/'))
    }
  }

  async function sendFile() {
    if (!uploadFile) return
    try {
      const fd = new FormData()
      fd.append('toUserId', peerId)
      fd.append('file', uploadFile)
      fd.append('content', '')
      await messageApi.sendForm(fd)
      setUploadFile(null)
      setUploadPreview('')
      setUploadIsVideo(false)
      await chatStore.fetchMessages(peerId)
      setTimeout(() => scrollBottom(true), 100)
    } catch {
      /* noop */
    }
  }

  function onSheetSelect(action: string) {
    setShowSheet(false)
    if (action === 'image') imageInputRef.current?.click()
    if (action === 'video') videoInputRef.current?.click()
  }

  const emojis = [
    '😀',
    '😂',
    '🤣',
    '😍',
    '🥰',
    '😎',
    '🤩',
    '👍',
    '🙏',
    '💪',
    '🔥',
    '🎉',
    '❤',
    '💔',
    '🎨',
    '💻',
    '📱',
    '💰',
    '⭐',
    '✅',
    '❌',
    '🤝',
    '🍳',
    '🚗',
    '☕',
    '📖',
    '🎵',
    '🌙',
    '✨',
    '🎂',
  ]

  return (
    <TemplateChatRightShell
      embedInLayout
      currentChat={{
        name: peerNickname,
        message: '',
        image: peerUser?.avatarUrl?.trim() || '',
      }}
      avatarFallback={peerNickname.slice(0, 2)}
      headerLeading={
        <Button
          variant="ghost"
          size="icon"
          type="button"
          className="shrink-0"
          aria-label="返回会话列表"
          onClick={() => navigate('/messages')}
        >
          <ChevronLeft className="h-5 w-5" />
        </Button>
      }
      middle={
        <div
          ref={listRef}
          className="thin-scroll flex min-h-0 flex-1 flex-col overflow-y-auto bg-bg-primary px-2 py-2"
        >
          {messages.map((m: ChatMessage, idx: number) => (
            <div key={m.id || m.createdAt}>
              <TimeDivider
                timestamp={m.createdAt}
                prevTimestamp={idx > 0 ? messages[idx - 1].createdAt : null}
              />
              <MessageBubble
                content={m.content}
                isMine={(m.senderId || m.fromUserId) === myId}
                type={m.type}
                nickname={peerNickname}
                avatarUrl={peerUser?.avatarUrl || ''}
                hideAvatar={
                  idx < messages.length - 1 &&
                  (messages[idx + 1]?.senderId ||
                    messages[idx + 1]?.fromUserId) ===
                    (m.senderId || m.fromUserId)
                }
              />
            </div>
          ))}
        </div>
      }
      inputRow={
        <>
          {uploadPreview ? (
            <div className="flex shrink-0 items-center gap-2 border-t border-border bg-bg-secondary px-3 py-2">
              {uploadIsVideo ? (
                <video
                  src={uploadPreview}
                  controls
                  muted
                  className="h-16 w-16 rounded-md object-cover"
                />
              ) : (
                <img
                  src={uploadPreview}
                  alt=""
                  className="h-16 w-16 rounded-md object-cover"
                />
              )}
              <button
                type="button"
                onClick={sendFile}
                className="rounded-md bg-[var(--primary-gradient)] px-3 py-1.5 text-sm font-semibold text-white"
              >
                发送
              </button>
              <button
                type="button"
                onClick={() => {
                  setUploadFile(null)
                  setUploadPreview('')
                  setUploadIsVideo(false)
                }}
                className="text-sm text-text-muted"
              >
                取消
              </button>
            </div>
          ) : null}

          {showEmoji && !showSheet ? (
            <div className="max-h-[200px] shrink-0 overflow-y-auto border-t border-border bg-card px-3 py-2">
              <div className="flex flex-wrap gap-0.5">
                {emojis.map((e) => (
                  <button
                    key={e}
                    type="button"
                    onClick={() => {
                      setInput(input + e)
                      setShowEmoji(false)
                    }}
                    className="cursor-pointer rounded-md px-2 py-1.5 text-[28px] hover:bg-bg-tertiary"
                  >
                    {e}
                  </button>
                ))}
              </div>
            </div>
          ) : null}

          <ActionSheet
            visible={showSheet}
            onClose={() => setShowSheet(false)}
            onSelect={onSheetSelect}
          />

          <div className="flex h-12 shrink-0 items-center gap-0.5 border-t border-border bg-card px-1">
            <Button
              variant="ghost"
              size="icon"
              type="button"
              onClick={() => {
                setShowEmoji(!showEmoji)
                setShowSheet(false)
              }}
              title="表情"
            >
              <Smile className="h-5 w-5" />
            </Button>

            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" size="icon" type="button" title="附件">
                  <Paperclip className="h-5 w-5" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuItem onSelect={() => imageInputRef.current?.click()}>
                  <Image className="mr-2 h-4 w-4" /> 照片与视频
                </DropdownMenuItem>
                <DropdownMenuItem onSelect={() => videoInputRef.current?.click()}>
                  <Camera className="mr-2 h-4 w-4" /> 视频
                </DropdownMenuItem>
                <DropdownMenuItem onSelect={() => imageInputRef.current?.click()}>
                  <File className="mr-2 h-4 w-4" /> 文件
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <UserRound className="mr-2 h-4 w-4" /> 联系人
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <ChartBarIncreasing className="mr-2 h-4 w-4" /> 投票
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <Brush className="mr-2 h-4 w-4" /> 画板
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>

            {isVoiceMode ? (
              <div
                onPointerDown={(e) => {
                  e.preventDefault()
                  void startRecording()
                }}
                onPointerUp={() => stopRecording()}
                onPointerLeave={() => stopRecording()}
                onContextMenu={(e) => e.preventDefault()}
                className={`flex h-9 min-w-0 flex-1 cursor-pointer select-none items-center justify-center rounded-lg text-sm font-semibold transition-colors ${
                  isRecording
                    ? 'bg-[var(--error-color)]/20 text-[var(--error-color)]'
                    : 'bg-bg-secondary text-text-secondary active:bg-bg-tertiary'
                }`}
              >
                {isRecording ? '松开 发送' : '按住 说话'}
              </div>
            ) : (
              <Input
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') void send()
                }}
                placeholder="输入消息…"
                className="h-9 min-w-0 flex-1 border-0 bg-transparent px-2 text-[15px] text-text-primary shadow-none focus-visible:ring-0"
              />
            )}

            {!input.trim() ? (
              <Button
                variant="ghost"
                size="icon"
                type="button"
                title="更多"
                onClick={() => {
                  setShowSheet(!showSheet)
                  setShowEmoji(false)
                }}
              >
                <span className="text-lg leading-none">＋</span>
              </Button>
            ) : null}

            <Button
              variant="ghost"
              size="icon"
              type="button"
              title="发送"
              onClick={() => void send()}
              disabled={!input.trim()}
            >
              <Send className="h-5 w-5" />
            </Button>

            <Button
              variant="ghost"
              size="icon"
              type="button"
              title={isVoiceMode ? '键盘输入' : '语音'}
              onClick={() => {
                setIsVoiceMode(!isVoiceMode)
                setShowEmoji(false)
                setShowSheet(false)
              }}
            >
              <Mic className="h-5 w-5" />
            </Button>
          </div>

          <input
            ref={imageInputRef}
            type="file"
            accept="image/*"
            hidden
            onChange={onFileChange}
          />
          <input
            ref={videoInputRef}
            type="file"
            accept="video/*"
            hidden
            onChange={onFileChange}
          />
        </>
      }
    />
  )
}

// archive/client-vue/src/views/ChatDetail.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, nextTick, watch, computed } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useUserStore } from '@/stores/user';
import { useChatStore } from '@/stores/chat';
import { messageApi } from '@/api/message';
import { userApi } from '@/api/user';
import ChatNavBar from '@/components/ChatNavBar.vue';
import TimeDivider from '@/components/TimeDivider.vue';
import MessageBubble from '@/components/MessageBubble.vue';
import ActionSheet from '@/components/ActionSheet.vue';

const route = useRoute();
const userStore = useUserStore();
const chatStore = useChatStore();
const peerId = computed(() => route.params.userId as string);
const router = useRouter();

const messages = computed(() => chatStore.messages.filter(m =>
  ((m.senderId || m.fromUserId) === userStore.user?.id && (m.receiverId || m.toUserId) === peerId.value) ||
  ((m.senderId || m.fromUserId) === peerId.value && (m.receiverId || m.toUserId) === userStore.user?.id)
));
const input = ref('');
const showEmoji = ref(false);
const showSheet = ref(false);
const isVoiceMode = ref(false);
const uploadFile = ref<File | null>(null);
const uploadPreview = ref('');
const uploadIsVideo = ref(false);
const listRef = ref<HTMLElement | null>(null);

// Fetch peer user info so nickname is available before any messages
const peerUser = ref<{ nickname: string; avatarUrl: string | null } | null>(null);
async function fetchPeerUser() {
  try {
    const res = await userApi.get(peerId.value);
    peerUser.value = res.data.data;
  } catch { peerUser.value = null; }
}
watch(peerId, fetchPeerUser, { immediate: true });

const peerInfo = computed(() => {
  const hit = messages.value.find((msg) => {
    const sid = msg.senderId || msg.fromUserId;
    const rid = msg.receiverId || msg.toUserId;
    const sidMatches = sid === peerId.value;
    const ridMatches = rid === peerId.value;
    return sidMatches || ridMatches;
  });
  if (!hit) {
    if (peerUser.value) return { nickname: peerUser.value.nickname, avatarUrl: peerUser.value.avatarUrl };
    return { nickname: '', avatarUrl: '' };
  }
  const sid = hit.senderId || hit.fromUserId;
  if (sid === peerId.value) {
    return { nickname: hit.fromUser?.nickname, avatarUrl: hit.fromUser?.avatarUrl ?? null };
  }
  return { nickname: hit.toUser?.nickname, avatarUrl: hit.toUser?.avatarUrl ?? null };
});

const peerNickname = computed(() => peerInfo.value.nickname || '聊天');
const peerAvatar = computed(() => peerInfo.value.avatarUrl || '');

const emojis = ['😀','😂','🤣','😍','🥰','😎','🤩','👍','🙏','💪','🔥','🎉','❤','💔','🎨','💻','📱','💰','⭐','✅','❌','🤝','🍳','🚗','☕','📖','🎵','🌙','✨','🎂'];

function insertEmoji(e: string) { input.value += e; showEmoji.value = false; }

function onFileChange(e: Event) {
  const f = (e.target as HTMLInputElement).files?.[0];
  if (f) {
    uploadFile.value = f;
    uploadPreview.value = URL.createObjectURL(f);
    uploadIsVideo.value = f.type.startsWith('video/');
  }
}

async function sendFile() {
  if (!uploadFile.value) return;
  try {
    const fd = new FormData();
    fd.append('toUserId', peerId.value);
    fd.append('file', uploadFile.value);
    fd.append('content', '');
    await messageApi.sendForm(fd);
    uploadFile.value = null; uploadPreview.value = ''; uploadIsVideo.value = false;
    chatStore.fetchMessages(peerId.value);
    nextTick(() => scrollBottom(true));
  } catch {}
}

async function send() {
  const text = input.value.trim();
  if (!text) return;
  try {
    const res = await messageApi.send(peerId.value, text);
    chatStore.messages = [...chatStore.messages, res.data.data];
    input.value = '';
    nextTick(() => scrollBottom(true));
  } catch {}
}

function onSheetSelect(action: string) {
  showSheet.value = false;
  if (action === 'image') document.getElementById('imageFileInput')?.click();
  if (action === 'video') document.getElementById('videoFileInput')?.click();
}

function scrollBottom(force = false) {
  if (!listRef.value) return;
  if (force) {
    listRef.value.scrollTop = listRef.value.scrollHeight;
    return;
  }
  // Only auto-scroll if user is near the bottom
  const el = listRef.value;
  const atBottom = el.scrollHeight - el.scrollTop - el.clientHeight < 120;
  if (atBottom) el.scrollTop = el.scrollHeight;
}

// Auto-scroll when new messages arrive
watch(() => messages.value.length, () => {
  nextTick(() => scrollBottom());
});

// Refresh messages when switching chats or gaining focus
let pollTimer: ReturnType<typeof setInterval> | null = null;
const pollActive = ref(false);

function startPolling() {
  if (pollActive.value || chatStore.connected) return;
  pollActive.value = true;
  pollTimer = setInterval(() => {
    chatStore.fetchMessages(peerId.value);
  }, 10000);
}

function stopPolling() {
  pollActive.value = false;
  if (pollTimer) { clearInterval(pollTimer); pollTimer = null; }
}

function onSocketDisconnect() { startPolling(); }
function onSocketConnect() { stopPolling(); }

watch([peerId, chatStore.connected], ([, connected]) => {
  if (connected) stopPolling(); else startPolling();
});

watch(peerId, () => {
  chatStore.fetchMessages(peerId.value);
  nextTick(() => scrollBottom(true));
  if (!chatStore.connected) startPolling();
});

onMounted(() => {
  if (peerId.value === userStore.user?.id) {
    router.replace('/messages');
    return;
  }
  chatStore.fetchMessages(peerId.value);
  nextTick(scrollBottom);
  if (!chatStore.connected) startPolling();
  document.addEventListener('visibilitychange', onVisible);
});

onUnmounted(() => {
  stopPolling();
  document.removeEventListener('visibilitychange', onVisible);
});

function onVisible() {
  if (document.visibilityState === 'visible') {
    chatStore.fetchMessages(peerId.value);
    if (!chatStore.connected) startPolling();
  } else {
    stopPolling();
  }
}
</script>

<template>
  <div class="chat-page full-width">
    <ChatNavBar :nickname="peerNickname" />

    <div ref="listRef" class="chat-list thin-scroll">
      <template v-for="(m, idx) in messages" :key="m.id || m.createdAt">
        <TimeDivider
          :timestamp="m.createdAt"
          :prev-timestamp="idx > 0 ? messages[idx - 1].createdAt : null"
        />
        <MessageBubble
          :content="m.content"
          :is-mine="(m.senderId || m.fromUserId) === userStore.user?.id"
          :type="m.type"
          :nickname="peerNickname"
          :avatar-url="peerAvatar"
          :hide-avatar="idx < messages.length - 1 && (messages[idx + 1].senderId || messages[idx + 1].fromUserId) === (m.senderId || m.fromUserId)"
        />
      </template>
    </div>

    <!-- Image preview bar -->
    <div v-if="uploadPreview" class="image-preview-bar">
      <video v-if="uploadIsVideo" :src="uploadPreview" controls muted class="preview-media" />
      <img v-else :src="uploadPreview" class="preview-media" loading="lazy" decoding="async" />
      <t-button size="small" theme="primary" @click="sendFile">发送</t-button>
      <t-button size="small" variant="text" @click="uploadFile = null; uploadPreview = ''; uploadIsVideo = false">取消</t-button>
    </div>

    <!-- Emoji panel -->
    <Transition name="slide-up">
      <div v-if="showEmoji && !showSheet" class="emoji-panel">
        <span v-for="e in emojis" :key="e" class="emoji-item" @click="insertEmoji(e)">{{ e }}</span>
      </div>
    </Transition>

    <!-- Action sheet -->
    <ActionSheet :visible="showSheet" @close="showSheet = false" @select="onSheetSelect" />

    <!-- Input bar -->
    <div class="input-bar">
      <button class="ibar-btn" @click="isVoiceMode = !isVoiceMode">
        <span v-if="isVoiceMode" style="font-size:18px">🎤</span>
        <svg v-else width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <rect x="9" y="1" width="6" height="11" rx="3"/><path d="M5 10a7 7 0 0 0 14 0"/>
        </svg>
      </button>

      <div v-if="isVoiceMode" class="voice-btn" @touchstart.prevent @mousedown.prevent>
        按住 说话
      </div>
      <div v-else class="input-wrap">
        <input
          v-model="input"
          class="text-input"
          placeholder="输入消息..."
          @keyup.enter="send"
        />
      </div>

      <button class="ibar-btn" @click="showEmoji = !showEmoji; showSheet = false">
        <span style="font-size:17px">😊</span>
      </button>

      <template v-if="input.trim()">
        <button class="send-btn" @click="send">发送</button>
      </template>
      <template v-else>
        <button class="ibar-btn" @click="showSheet = !showSheet; showEmoji = false">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="16"/><line x1="8" y1="12" x2="16" y2="12"/>
          </svg>
        </button>
      </template>

      <input id="imageFileInput" type="file" accept="image/*" hidden @change="onFileChange" />
      <input id="videoFileInput" type="file" accept="video/*" hidden @change="onFileChange" />
    </div>
  </div>
</template>

<style scoped>
.chat-page {
  display: flex; flex-direction: column; height: 100%;
  background: var(--bg-primary);
}

/* ── Message list ── */
.chat-list {
  flex: 1; overflow-y: auto; padding: 8px 0;
  display: flex; flex-direction: column;
}

/* ── Image preview ── */
.image-preview-bar {
  display: flex; gap: 8px; align-items: center;
  padding: 8px 16px;
  border-top: 1px solid var(--border-color);
  background: var(--bg-secondary);
}
.preview-media {
  width: 64px; height: 64px; border-radius: 6px; object-fit: cover;
}

/* ── Emoji panel ── */
.emoji-panel {
  display: flex; flex-wrap: wrap; gap: 2px;
  padding: 10px 12px;
  border-top: 1px solid var(--border-color);
  background: var(--bg-card);
  max-height: 200px; overflow-y: auto;
}
.emoji-item {
  font-size: 28px; cursor: pointer; padding: 6px 8px;
  border-radius: 6px; transition: background 0.1s;
}
.emoji-item:hover { background: var(--bg-tertiary); }

/* ── Slide-up transition ── */
.slide-up-enter-active,
.slide-up-leave-active { transition: all 0.25s ease; }
.slide-up-enter-from,
.slide-up-leave-to { opacity: 0; transform: translateY(20px); }

/* ── Input bar ── */
.input-bar {
  display: flex; gap: 4px; align-items: center;
  padding: 8px 10px;
  background: var(--bg-card);
  border-top: 1px solid var(--border-color);
}

.ibar-btn {
  width: 40px; height: 40px; flex-shrink: 0;
  display: flex; align-items: center; justify-content: center;
  background: none; border: none; color: var(--text-secondary);
  cursor: pointer; border-radius: 50%; transition: background 0.15s;
}
.ibar-btn:hover { background: var(--bg-tertiary); }

.input-wrap {
  flex: 1; min-width: 0;
}
.text-input {
  width: 100%; height: 36px; padding: 0 12px;
  background: var(--bg-secondary); border: none; border-radius: 18px;
  color: var(--text-primary); font-size: 15px; outline: none;
}
.text-input::placeholder { color: var(--text-muted); }

.voice-btn {
  flex: 1; height: 36px; display: flex; align-items: center; justify-content: center;
  background: var(--bg-secondary); border-radius: 8px;
  color: var(--text-secondary); font-size: 14px; font-weight: 600;
  cursor: pointer; user-select: none;
}
.voice-btn:active { background: var(--bg-tertiary); }

.send-btn {
  height: 36px; padding: 0 18px; flex-shrink: 0;
  background: var(--success-color); border: none; border-radius: 6px;
  color: #000; font-size: 14px; font-weight: 600; cursor: pointer;
  transition: opacity 0.15s;
}
.send-btn:hover { opacity: 0.85; }
</style>
