// client-react/src/components/ui/action-sheet.tsx
import { Image, Video } from 'lucide-react'

interface ActionSheetProps {
  visible: boolean
  onClose: () => void
  onSelect: (action: string) => void
}

const actions = [
  { key: 'image', label: '图片', icon: Image },
  { key: 'video', label: '视频', icon: Video },
]

export function ActionSheet({ visible, onClose, onSelect }: ActionSheetProps) {
  if (!visible) return null
  return (
    <div
      className="fixed inset-0 z-[var(--z-sticky)] bg-background/55 animate-fadeIn"
      onClick={onClose}
    >
      <div
        className="absolute bottom-0 left-0 right-0 bg-card rounded-t-2xl pt-5 px-4 pb-8 border-t border-border animate-slideUp"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="grid grid-cols-2 gap-4">
          {actions.map(({ key, label, icon: Icon }) => (
            <button
              key={key}
              onClick={() => onSelect(key)}
              className="flex flex-col items-center gap-2 bg-transparent border-none text-text-primary cursor-pointer py-3 px-2 rounded-xl hover:bg-bg-tertiary"
            >
              <Icon className="size-5" />
              <span className="text-sm text-text-secondary">{label}</span>
            </button>
          ))}
        </div>
      </div>
    </div>
  )
}

// archive/client-vue/src/components/ActionSheet.vue
<script setup lang="ts">
defineProps<{ visible: boolean }>();
const emit = defineEmits<{ close: []; select: [action: string] }>();

const actions = [
  { key: 'image', label: '图片', icon: '🖼' },
  { key: 'video', label: '视频', icon: '🎬' },
];
</script>

<template>
  <Transition name="sheet">
    <div v-if="visible" class="sheet-overlay" @click="emit('close')">
      <div class="sheet-panel" @click.stop>
        <div class="sheet-grid">
          <button
            v-for="a in actions" :key="a.key"
            class="sheet-item"
            @click="emit('select', a.key)"
          >
            <span class="sheet-icon">{{ a.icon }}</span>
            <span class="sheet-label">{{ a.label }}</span>
          </button>
        </div>
      </div>
    </div>
  </Transition>
</template>

<style scoped>
.sheet-overlay {
  position: fixed; inset: 0; z-index: 100;
  background: rgba(0,0,0,0.3);
}
.sheet-panel {
  position: absolute; bottom: 0; left: 0; right: 0;
  background: var(--bg-card); border-radius: 16px 16px 0 0;
  padding: 20px 16px 32px;
  border-top: 1px solid var(--border-color);
}
.sheet-grid {
  display: grid; grid-template-columns: repeat(2, 1fr); gap: 16px;
}
.sheet-item {
  display: flex; flex-direction: column; align-items: center; gap: 8px;
  background: none; border: none; color: var(--text-primary); cursor: pointer;
  padding: 12px 8px; border-radius: 12px; transition: background 0.15s;
}
.sheet-item:hover { background: var(--bg-tertiary); }
.sheet-icon { font-size: 32px; }
.sheet-label { font-size: 12px; color: var(--text-secondary); }

/* Transition */
.sheet-enter-active, .sheet-leave-active { transition: opacity 0.25s ease; }
.sheet-enter-from, .sheet-leave-to { opacity: 0; }
.sheet-enter-active .sheet-panel, .sheet-leave-active .sheet-panel {
  transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}
.sheet-enter-from .sheet-panel, .sheet-leave-to .sheet-panel {
  transform: translateY(100%);
}
</style>
