// client-react/src/components/ui/chat-navbar.tsx
import { useNavigate } from 'react-router-dom'

interface ChatNavBarProps {
  nickname: string
  className?: string
}

export function ChatNavBar({ nickname, className }: ChatNavBarProps) {
  const navigate = useNavigate()
  return (
    <div
      className={`sticky top-0 z-50 flex items-center justify-between h-12 px-1 border-b border-border bg-card/80 backdrop-blur-md ${className || ''}`}
    >
      <button
        onClick={() => navigate(-1)}
        className="w-10 h-10 flex items-center justify-center bg-transparent border-none text-text-primary cursor-pointer rounded-full hover:bg-bg-tertiary"
      >
        <svg
          width="20"
          height="20"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2.5"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <polyline points="15 18 9 12 15 6" />
        </svg>
      </button>
      <span className="text-base font-semibold text-text-primary max-w-[50%] overflow-hidden text-ellipsis whitespace-nowrap">
        {nickname}
      </span>
      <button className="w-10 h-10 flex items-center justify-center bg-transparent border-none text-text-primary cursor-pointer rounded-full hover:bg-bg-tertiary">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor">
          <circle cx="12" cy="5" r="2" />
          <circle cx="12" cy="12" r="2" />
          <circle cx="12" cy="19" r="2" />
        </svg>
      </button>
    </div>
  )
}

// archive/client-vue/src/components/ChatNavBar.vue
<script setup lang="ts">
import { useRouter } from 'vue-router';

defineProps<{ nickname: string }>();
const router = useRouter();
</script>

<template>
  <div class="chat-navbar glass">
    <button class="nav-btn" @click="router.back()">
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="15 18 9 12 15 6"/></svg>
    </button>
    <span class="nav-title">{{ nickname }}</span>
    <button class="nav-btn">
      <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><circle cx="12" cy="5" r="2"/><circle cx="12" cy="12" r="2"/><circle cx="12" cy="19" r="2"/></svg>
    </button>
  </div>
</template>

<style scoped>
.chat-navbar {
  position: sticky; top: 0; z-index: 50;
  display: flex; align-items: center; justify-content: space-between;
  height: 48px; padding: 0 4px;
  border-bottom: 1px solid var(--border-color);
}
.nav-btn {
  width: 40px; height: 40px; display: flex; align-items: center; justify-content: center;
  background: none; border: none; color: var(--text-primary); cursor: pointer;
  border-radius: 50%; transition: background 0.15s;
}
.nav-btn:hover { background: var(--bg-tertiary); }
.nav-title {
  font-size: 16px; font-weight: 600; color: var(--text-primary);
  max-width: 50%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
}
</style>
