// client-react/src/components/ui/error-state.tsx
import { AlertCircle } from 'lucide-react'
import { Button } from '@/components/ui/button'

interface ErrorStateProps {
  message?: string
  onRetry?: () => void
}

export function ErrorState({ message = '加载失败', onRetry }: ErrorStateProps) {
  return (
    <div className="flex flex-col items-center justify-center py-16">
      <AlertCircle className="size-8 text-error mb-3" />
      <p className="text-sm text-text-muted mb-4">{message}</p>
      {onRetry && (
        <Button variant="outline" size="sm" onClick={onRetry}>
          重试
        </Button>
      )}
    </div>
  )
}

// archive/client-vue/src/components/ErrorState.vue
<script setup lang="ts">
defineProps<{ message?: string }>();
defineEmits<{ retry: [] }>();
</script>

<template>
  <div class="error-state">
    <div class="error-icon">⚠</div>
    <p class="error-message">{{ message || '加载失败' }}</p>
    <t-button theme="primary" variant="outline" @click="$emit('retry')">重试</t-button>
  </div>
</template>

<style scoped>
.error-state { text-align: center; padding: 60px 20px; }
.error-icon { font-size: 48px; margin-bottom: 12px; }
.error-message { color: var(--error-color); margin: 0 0 16px; font-size: 14px; }
</style>
