// archive/client-vue/src/views/OrderDetail.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { orderApi } from '@/api/order';
import { useUserStore } from '@/stores/user';
import { MessagePlugin, DialogPlugin } from 'tdesign-vue-next';
import LoadingState from '@/components/LoadingState.vue';
import ErrorState from '@/components/ErrorState.vue';

const route = useRoute();
const router = useRouter();
const userStore = useUserStore();

const order = ref<any>(null);
const loading = ref(true);
const error = ref('');

const isProvider = computed(() => order.value?.providerId === userStore.user?.id);
const isRequester = computed(() => order.value?.requesterId === userStore.user?.id);

async function fetchOrder() {
  loading.value = true;
  error.value = '';
  try {
    const res = await orderApi.get(route.params.id as string);
    order.value = res.data.data;
  } catch {
    error.value = '加载失败，请确认订单存在';
  } finally { loading.value = false; }
}

async function prepay() {
  try {
    await orderApi.prepay(order.value.id);
    MessagePlugin.success('支付成功（模拟）');
    fetchOrder();
  } catch (e: any) { MessagePlugin.error(e.response?.data?.message); }
}

async function complete() {
  try {
    await orderApi.complete(order.value.id);
    MessagePlugin.success('已标记完成');
    fetchOrder();
  } catch (e: any) { MessagePlugin.error(e.response?.data?.message); }
}

async function confirm() {
  try {
    await orderApi.confirm(order.value.id);
    MessagePlugin.success('订单已完成');
    fetchOrder();
  } catch (e: any) { MessagePlugin.error(e.response?.data?.message); }
}

async function dispute() {
  const dlg = DialogPlugin.confirm({
    header: '发起争议', body: '确认发起争议？', onConfirm: async () => {
      dlg.hide();
      try {
        await orderApi.dispute(order.value.id);
        MessagePlugin.success('争议已提交');
        fetchOrder();
      } catch (e: any) { MessagePlugin.error(e.response?.data?.message); }
    },
    onClose: () => dlg.hide(),
  });
}

const showPartial = ref(false);
const partialForm = ref({ newPrice: 0, description: '' });

async function submitPartial() {
  try {
    await orderApi.partial(order.value.id, partialForm.value.newPrice, partialForm.value.description);
    MessagePlugin.success('部分完成已提交');
    showPartial.value = false;
    fetchOrder();
  } catch (e: any) { MessagePlugin.error(e.response?.data?.message); }
}

const statusLabel: Record<string, string> = {
  PENDING: '待确认', IN_PROGRESS: '服务中', WAITING_REVIEW: '待验收',
  COMPLETED: '已完成', DISPUTED: '争议中',
};

onMounted(fetchOrder);
</script>

<template>
  <div class="order-detail">
    <ErrorState v-if="error" :message="error" @retry="fetchOrder" />
    <LoadingState v-else-if="loading" />

    <div v-else-if="order" class="order-card glass">
      <div class="back-row">
        <t-button variant="text" @click="router.back()">← 返回</t-button>
      </div>
      <h2>{{ order.demand?.title }}</h2>
      <div class="status-row">
        <t-tag :theme="order.status === 'COMPLETED' ? 'success' : order.status === 'DISPUTED' ? 'danger' : 'primary'">
          {{ statusLabel[order.status] || order.status }}
        </t-tag>
      </div>

      <div class="info-grid">
        <div class="info"><span class="lbl">金额</span><span class="val">¥{{ order.agreedPrice }}</span></div>
        <div class="info"><span class="lbl">服务方</span><span class="val">{{ order.provider?.nickname }}</span></div>
        <div class="info"><span class="lbl">需求方</span><span class="val">{{ order.requester?.nickname }}</span></div>
        <div class="info" v-if="order.paidAt"><span class="lbl">支付时间</span><span class="val">{{ new Date(order.paidAt).toLocaleString() }}</span></div>
        <div class="info" v-if="order.completedAt"><span class="lbl">完成时间</span><span class="val">{{ new Date(order.completedAt).toLocaleString() }}</span></div>
      </div>

      <div class="actions">
        <!-- Requester: prepay if in progress -->
        <t-button v-if="isRequester && order.status === 'IN_PROGRESS' && !order.paidAt" theme="primary" @click="prepay">
          模拟支付 (预付50%)
        </t-button>
        <!-- Provider: mark complete -->
        <t-button v-if="isProvider && order.status === 'IN_PROGRESS' && order.paidAt" theme="primary" @click="complete">
          标记完成
        </t-button>
        <!-- Requester: confirm -->
        <t-button v-if="isRequester && order.status === 'WAITING_REVIEW'" theme="success" @click="confirm">
          确认验收
        </t-button>
        <!-- Dispute -->
        <t-button v-if="(isProvider || isRequester) && ['IN_PROGRESS', 'WAITING_REVIEW'].includes(order.status)" theme="danger" variant="outline" @click="dispute">
          发起争议
        </t-button>
        <!-- Partial complete (provider) -->
        <t-button v-if="isProvider && order.status === 'IN_PROGRESS'" variant="outline" @click="showPartial = true">
          部分完成
        </t-button>
      </div>
    </div>

    <!-- Partial complete dialog -->
    <t-dialog v-model:visible="showPartial" header="部分完成" :footer="false">
      <div class="partial-form">
        <t-input v-model="partialForm.newPrice" placeholder="新价格（低于原价）" type="number" />
        <t-textarea v-model="partialForm.description" placeholder="说明剩余部分" />
        <t-button theme="primary" block @click="submitPartial">提交</t-button>
      </div>
    </t-dialog>
  </div>
</template>

<style scoped>
.order-detail { height: 100%; overflow-y: auto; padding: 20px; }
.order-card { max-width: 500px; margin: 0 auto; padding: 24px; border-radius: var(--radius); }
.back-row { margin-bottom: 12px; }
h2 { margin: 0 0 16px; }
.status-row { margin-bottom: 16px; }
.info-grid { display: flex; flex-direction: column; gap: 8px; margin-bottom: 20px; }
.info { display: flex; justify-content: space-between; }
.lbl { color: var(--text-muted); font-size: 13px; }
.val { font-weight: 600; }
.actions { display: flex; flex-direction: column; gap: 8px; }
.partial-form { display: flex; flex-direction: column; gap: 12px; }
</style>

// client-react/src/views/OrderDetail.tsx
import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { orderApi } from '@/api/order'
import { useUserStore } from '@/stores/user'
import { toast } from '@/components/ui/confirm-dialog'

const statusLabel: Record<string, string> = { PENDING: '待确认', IN_PROGRESS: '服务中', WAITING_REVIEW: '待验收', COMPLETED: '已完成', DISPUTED: '争议中' }

export default function OrderDetail() {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const user = useUserStore((s) => s.user)
  const [order, setOrder] = useState<any>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [showPartial, setShowPartial] = useState(false)
  const [partial, setPartial] = useState({ newPrice: 0, description: '' })

  const isProvider = order?.providerId === user?.id
  const isRequester = order?.requesterId === user?.id

  async function fetchOrder() {
    if (!id) return; setLoading(true); setError('')
    try { const r = await orderApi.get(id); setOrder(r.data.data) }
    catch { setError('加载失败') }
    finally { setLoading(false) }
  }

  useEffect(() => { fetchOrder() }, [id])

  async function act(fn: () => Promise<any>, msg: string) {
    try { await fn(); toast(msg); fetchOrder() } catch (e: any) { toast(e.response?.data?.message || '操作失败', 'error') }
  }

  if (loading) return <div className="text-center py-16 text-text-muted text-sm">加载中...</div>
  if (error) return <div className="text-center py-16"><p className="text-text-muted text-sm">{error}</p><button onClick={fetchOrder} className="mt-3 text-accent text-sm">重试</button></div>
  if (!order) return null

  const s = order.status
  const statusTheme = (st: string) => {
    const m: Record<string, string> = { COMPLETED: 'bg-emerald-500/15 text-emerald-400', DISPUTED: 'bg-red-500/15 text-red-400', IN_PROGRESS: 'bg-blue-500/15 text-blue-400', WAITING_REVIEW: 'bg-amber-500/15 text-amber-400' }
    return m[st] || 'bg-card text-text-muted'
  }

  return (
    <div className="h-full overflow-y-auto thin-scroll max-w-3xl mx-auto p-5">
      <div className="max-w-[500px] mx-auto glass p-6 rounded-xl">
        <button onClick={() => navigate(-1)} className="text-text-muted text-sm mb-3 hover:text-text-secondary">← 返回</button>
        <h2 className="mb-4 text-lg font-bold">{order.demand?.title}</h2>
        <div className="mb-4"><span className={`px-2 py-0.5 rounded text-[10px] font-semibold ${statusTheme(s)}`}>{statusLabel[s] || s}</span></div>

        <div className="flex flex-col gap-2 mb-5">
          <div className="flex justify-between"><span className="text-[13px] text-text-muted">金额</span><span className="font-semibold">¥{order.agreedPrice}</span></div>
          <div className="flex justify-between"><span className="text-[13px] text-text-muted">服务方</span><span className="font-semibold">{order.provider?.nickname}</span></div>
          <div className="flex justify-between"><span className="text-[13px] text-text-muted">需求方</span><span className="font-semibold">{order.requester?.nickname}</span></div>
          {order.paidAt && <div className="flex justify-between"><span className="text-[13px] text-text-muted">支付时间</span><span className="font-semibold">{new Date(order.paidAt).toLocaleString()}</span></div>}
          {order.completedAt && <div className="flex justify-between"><span className="text-[13px] text-text-muted">完成时间</span><span className="font-semibold">{new Date(order.completedAt).toLocaleString()}</span></div>}
        </div>

        <div className="flex flex-col gap-2">
          {isRequester && s === 'IN_PROGRESS' && !order.paidAt && <button onClick={() => act(() => orderApi.prepay(order.id), '支付成功（模拟）')} className="w-full py-2.5 rounded-lg bg-[var(--primary-gradient)] text-white font-semibold text-sm">模拟支付 (预付50%)</button>}
          {isProvider && s === 'IN_PROGRESS' && order.paidAt && <button onClick={() => act(() => orderApi.complete(order.id), '已标记完成')} className="w-full py-2.5 rounded-lg bg-[var(--primary-gradient)] text-white font-semibold text-sm">标记完成</button>}
          {isRequester && s === 'WAITING_REVIEW' && <button onClick={() => act(() => orderApi.confirm(order.id), '订单已完成')} className="w-full py-2.5 rounded-lg bg-emerald-500 text-white font-semibold text-sm">确认验收</button>}
          {(isProvider || isRequester) && ['IN_PROGRESS', 'WAITING_REVIEW'].includes(s) && <button onClick={() => act(() => orderApi.dispute(order.id), '争议已提交')} className="w-full py-2.5 rounded-lg border border-red-500/50 bg-transparent text-red-400 font-semibold text-sm">发起争议</button>}
          {isProvider && s === 'IN_PROGRESS' && <button onClick={() => setShowPartial(true)} className="w-full py-2.5 rounded-lg border border-border bg-transparent text-text-secondary font-semibold text-sm">部分完成</button>}
        </div>
      </div>

      {showPartial && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50" onClick={() => setShowPartial(false)}>
          <div className="bg-bg-secondary rounded-2xl p-6 w-[90%] max-w-sm border border-border" onClick={e => e.stopPropagation()}>
            <h3 className="text-lg font-bold mb-4">部分完成</h3>
            <div className="flex flex-col gap-3">
              <input type="number" value={partial.newPrice} onChange={e => setPartial({ ...partial, newPrice: Number(e.target.value) })} placeholder="新价格（低于原价）" className="bg-card border border-border rounded-lg px-4 py-2.5 text-text-primary text-sm outline-none" />
              <textarea value={partial.description} onChange={e => setPartial({ ...partial, description: e.target.value })} placeholder="说明剩余部分" rows={2} className="bg-card border border-border rounded-lg px-4 py-2.5 text-text-primary text-sm outline-none resize-none" />
              <button onClick={() => act(() => orderApi.partial(order.id, partial.newPrice, partial.description), '部分完成已提交')} className="w-full py-2.5 rounded-lg bg-[var(--primary-gradient)] text-white font-semibold text-sm">提交</button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
